[tool.ruff]
line-length = 120
select = ["E", "F", "I", "UP"]
ignore = ["D203"]
extend-exclude = ["src/flaskapp/migrations/"]

[tool.ruff.isort]

[tool.pytest.ini_options]
addopts = "-ra -vv"
DJANGO_SETTINGS_MODULE = "project.settings"
pythonpath = ["src"]

[tool.coverage.report]
show_missing = true
